version: 0.2

env:
  variables:
    DISCORD_CLIENT_ID: "908517049687494656"
    DISCORD_GUILD_ID: "896118395530002462"
    DISCORD_INVITE_CHANNEL_ID: "896118395978784800"
    AWS_DEFAULT_REGION: "eu-central-1"
    AWS_ACCOUNT_ID: "668064706315"
    IMAGE_REPO_NAME: "creasury"
    IMAGE_TAG: "latest"
  secrets-manager:
    DISCORD_TOKEN: "arn:aws:secretsmanager:eu-central-1:668064706315:secret:creasury-bot/dev-9EGGqq:DISCORD_TOKEN"

phases:
  install:
    runtime-versions:
      nodejs: 16.x
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG